name: Preview Pull Requests

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, closed]

permissions:
  contents: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

jobs:
  build-and-preview:
    name: Build and preview pull request
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        env:
          BASE_URL: /docu-notion-sample/pr-preview/pr-${{ github.event.number }}
        run: yarn build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: build
          umbrella-dir: pr-preview

  remove-preview:
    name: Remove Pull Request Preview
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v3
      - name: Remove Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: remove
